Music_2.FrontAdmin/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Music_2.ApiIntegration.Category;
using Music_2.Data.EF;
using Music_2.Data.Entities;
using Music_2.Data.Models.Catalog.Categories;
using Music_2.Data.Models.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Music_2.FrontAdmin.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly ICategoryApiClient _categoryApiClient;
        private readonly IConfiguration _configuration;
        private readonly OnlineMusicDbContext _context;

        public CategoriesController(ICategoryApiClient categoryApiClient, IConfiguration configuration, OnlineMusicDbContext context)
        {
            _categoryApiClient = categoryApiClient;
            _configuration = configuration;
            _context = context;
        }
        public async Task<IActionResult> Index(string keyword, string languageId, int pageIndex = 1, int pageSize = 5)
        {
            var request = new GetCategoriesPagingRequest()
            {
                Keyword = keyword,
                PageIndex = pageIndex,
                LanguageId = languageId,
                PageSize = pageSize
            };
            var data = await _categoryApiClient.GetAllPaging(request);
            ViewBag.Keyword = keyword;
            if (TempData["result"] != null)
            {
                ViewBag.SuccessMsg = TempData["result"];
            }
            return View(data);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [Consumes("multipart/form-data")]
        public async Task<IActionResult> Create(CategoryCreateRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _categoryApiClient.Create(request);
            if (result)
            {
                TempData["result"] = "Thêm mới danh mục sản phẩm thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Thêm danh mục sản phẩm thất bại");
            return View(request);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var languageId = HttpContext.Session.GetString(SystemConstants.AppSettings.DefaultLanguageId);
            var result = await _categoryApiClient.GetById(languageId, id);
            var editVm = new CategoryUpdateRequest()
            {
                Id = result.Id,
                Name = result.Name,
                SeoAlias = result.SeoAlias,
                SeoDescription = result.SeoDescription,
                SeoTitle = result.SeoTitle
            };
            return View(editVm);
        }
        [HttpPost]
        public async Task<IActionResult> Edit([FromForm] CategoryUpdateRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _categoryApiClient.Update( request);
            if (result)
            {
                TempData["result"] = "Cập nhật danh mục thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Cập nhật danh không mục thành công");
            return View(request);

        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(new CategoryDeleteRequest()
            {
                Id = id
            });
        }

        [HttpPost]
        public async Task<IActionResult> Delete(CategoryDeleteRequest request)
        {
            if (!ModelState.IsValid)
                return View();

            var result = await _categoryApiClient.Delete(request.Id);
            if (result)
            {
                TempData["result"] = "Xóa danh mục thành công";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Xóa không thành công");
            return View(request);
        }

        //export
        public IActionResult ExportCsv()
        {
            var users = _context.Categories.ToList();
            var builder = new StringBuilder();
            builder.AppendLine("Id,Name");
            foreach (var user in users)
            {
                builder.AppendLine($"{user.Id},{user.Name}");
            }
            var name = "categories";
            return File(Encoding.UTF8.GetBytes(builder.ToString()), "text/csv", $"{name}.csv");
        }
    }
}

Music_2.FrontAdmin/Controllers/Component/PagerViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Music_2.Data.Models.CommonApi;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music_2.FrontAdmin.Controllers.Component
{
    public class PagerViewComponent : ViewComponent
    {
        public Task<IViewComponentResult> InvokeAsync(PagedResultBase result)
        {
            return Task.FromResult((IViewComponentResult)View("Default", result));
        }
    }
}

Music_2.FrontAdmin/Controllers/Components/NavigationViewComponent.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Music_2.ApiIntegration.Language;
using Music_2.Data.Models.Utils;
using Music_2.FrontAdmin.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music_2.FrontAdmin.Controllers.Components
{
    public class NavigationViewComponent : ViewComponent
    {
        private readonly ILanguageApiClient _languageApiClient;

        public NavigationViewComponent(ILanguageApiClient languageApiClient)
        {
            _languageApiClient = languageApiClient;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var languages = await _languageApiClient.GetAll();
            var currentLanguageId = HttpContext
                .Session
                .GetString(SystemConstants.AppSettings.DefaultLanguageId);
            var items = languages.ResultObj.Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString(),
                Selected = currentLanguageId == null ? x.IsDefault : currentLanguageId == x.Id.ToString()
            });
            var navigationVm = new NavigationViewModel()
            {
                LanguageId = currentLanguageId,
                Languages = items.ToList()
            };

            return View("Default", navigationVm);
        }
    }
}

Music_2.FrontAdmin/Views/Categories/Create.cshtml
@model Music_2.Data.Models.Catalog.Categories.CategoryCreateRequest

@{
    ViewData["Title"] = "Thêm mới danh mục sản phẩm";
}

@using (Html.BeginForm("Create", "Categories", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Thêm mới danh mục sản phẩm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SeoTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SeoTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SeoTitle, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.SeoDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SeoDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SeoDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SeoAlias, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SeoAlias, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SeoAlias, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LanguageId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LanguageId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LanguageId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsFeatured, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsFeatured, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsFeatured, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="  Create  " class="btn btn-success btn-icon-split" />
            </div>
        </div>
    </div>}
<div>
    <a asp-action="Index">← Back to List</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Music_2.FrontAdmin/Views/Categories/Delete.cshtml
@model Music_2.Data.Models.Catalog.Categories.CategoryDeleteRequest

@{
    ViewData["Title"] = "Delete";
}
<h3>Bạn có chắc chắn muốn xóa danh mục này?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
        </dt>

    </dl>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div>
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-success btn-icon-split" /> |
                @Html.ActionLink("← Back to List", "Index")
            </div>
        </div>}
</div>

Music_2.FrontAdmin/Views/Categories/Edit.cshtml
@model Music_2.Data.Models.Catalog.Categories.CategoryUpdateRequest

@{
    ViewData["Title"] = "Sửa thông tin danh mục";
}
<div class="form-horizontal">
    <h4>Sửa thông tin danh mục sản phẩm</h4>
    <hr />
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Edit" enctype="multipart/form-data" method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Id" class="control-label"></label>
                    <input asp-for="Id" class="form-control" />
                    <span asp-validation-for="Id" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label"></label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SeoDescription" class="control-label"></label>
                    <input asp-for="SeoDescription" class="form-control" />
                    <span asp-validation-for="SeoDescription" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SeoTitle" class="control-label"></label>
                    <input asp-for="SeoTitle" class="form-control" />
                    <span asp-validation-for="SeoTitle" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SeoAlias" class="control-label"></label>
                    <input asp-for="SeoAlias" class="form-control" />
                    <span asp-validation-for="SeoAlias" class="text-danger"></span>
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.IsFeatured, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.IsFeatured, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IsFeatured, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="  Save  " class="btn btn-success btn-icon-split" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<div>
    <a asp-action="Index">← Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Music_2.FrontAdmin/Views/Categories/Index.cshtml
@using Music_2.Data.Models.CommonApi
@model PagedResult<Music_2.Data.Models.Catalog.Categories.CategoryViewModel>

@{
    ViewData["Title"] = "Danh sách danh mục sản phẩm";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts{
    <script>
        setTimeout(function () {
            $('#msgAlert').fadeOut('slow');
        }, 2000);
    </script>
}

<div class="d-sm-flex align-items-center justify-content-between">
    <button class="btn btn-light" type="button">
        @Html.ActionLink("Thêm danh mục", "Create")
    </button>
    <button class="btn btn-light" type="button">
        <i class="fas fa-download fa-sm text-white-50"></i>
        @Html.ActionLink(" Generate Report", "ExportCsv")
    </button>
</div>
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <form asp-action="Index" method="get" class="form-inline mr-auto w-100 navbar-search">
            <div class="input-group">
                <input name="keyword" type="text" class="form-control bg-light border-0 small" value="@ViewBag.Keyword" placeholder="Search for..."
                       aria-label="Search" aria-describedby="basic-addon2" style="width:360px">
                <div class="input-group-append">
                    <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                    </button>
                </div>
            </div>
            <button type="submit" onclick="/Categories/Index" class="btn"> Reset </button>
            @await Component.InvokeAsync("Navigation", Model)
        </form>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            @if (ViewBag.SuccessMsg != null)
            {
                <div id="msgAlert" class="alert alert-success" role="alert">
                    @ViewBag.SuccessMsg
                </div>
            }
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>Tên</th>
                        <th>SeoTitle</th>
                        <th>SeoDescription</th>
                        <th>SeoAlias</th>
                        <th></th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model.Items)
                    {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.SeoTitle</td>
                        <td>@item.SeoDescription</td>
                        <td>@item.SeoAlias</td>
                        <td>
                            <a href="/Categories/Edit?id=@item.Id">Sửa</a>
                            |
                            <a href="/Categories/Delete?id=@item.Id"> Xóa</a>
                        </td>

                    </tr>
                    }

                </tbody>
            </table>
            <center>@await Component.InvokeAsync("Pager", Model)</center>
        </div>
    </div>
</div>